#
# heka config
#
[hekad]
maxprocs = {{ ansible_processor_vcpus }}

{% if heka_monitor_disk | bool %}
#
# Disk Stats
#
[diskstats-decoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_diskstats.lua"

{% for device in ansible_devices %}
[diskstats-{{ device }}-input]
type = "FilePollingInput"
ticker_interval = {{ heka_diskstats_interval }}
file_path = "/sys/block/{{ device }}/stat"
decoder = "diskstats-decoder"

[diskstats-{{ device }}-filter]
type = "SandboxFilter"
filename = "lua_filters/diskstats.lua"
ticker_interval = {{ heka_diskstats_interval }}
preserve_data = true
message_matcher = "Logger == 'diskstats-{{ device }}-input'"

{% endfor %}
{% endif %}

{% if heka_monitor_cpu %}
#
# Load Average
#
[loadavg-decoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_loadavg.lua"

[loadavg-input]
type = "FilePollingInput"
ticker_interval = {{ heka_cpustats_interval }}
file_path = "/proc/loadavg"
decoder = "loadavg-decoder"

[loadavg]
type = "SandboxFilter"
filename = "lua_filters/loadavg.lua"
ticker_interval = {{ heka_cpustats_interval }}
preserve_data = true
message_matcher = "Type == 'stats.loadavg'"

#
# Proc stats
#
[procstats-decoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_procstat.lua"

[procstats-input]
type = "FilePollingInput"
ticker_interval = {{ heka_cpustats_interval }}
file_path = "/proc/stat"
decoder = "procstats-decoder"

[procstats]
type = "SandboxFilter"
filename = "lua_filters/procstat.lua"
preserve_data = true
message_matcher = "Type == 'stats.procstat'"
ticker_interval = {{ heka_cpustats_interval }}

[procstats.config]
    whitelist = "cpu$"
    extras = false
    percent_integer = true
{% endif %}

{% if heka_monitor_memory | bool %}
#
# Memory Stats
#
[memory-stats-decoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_memstats.lua"

[memory-stats-input]
type = "FilePollingInput"
ticker_interval = {{ heka_memorystats_interval }}
file_path = "/proc/meminfo"
decoder = "memory-stats-decoder"

[memory-stats]
type = "SandboxFilter"
filename = "lua_filters/memstats.lua"
ticker_interval = {{ heka_memorystats_interval }}
preserve_data = true
message_matcher = "Type == 'stats.memstats'"
{% endif %}

#
# Outputs
#
{% if heka_debug | bool %}
[rst-encoder]
type = "RstEncoder"

[heka-debug-output]
type = "LogOutput"
encoder = "rst_encoder"
message_matcher = "TRUE"
{% endif %}

{% if heka_dashboard_enabled | bool %}
[dashboard]
type = "DashboardOutput"
ticker_interval = {{ heka_dashboard_interval }}
address = "{{ heka_dashboard_address }}"
{% endif %}
